// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLpFhV9aXaQ9nTv2Ss5hjWWTStvT79tB4',
    appId: '1:136918825702:web:c63543e85cc3b583e95927',
    messagingSenderId: '136918825702',
    projectId: 'health-6cd34',
    authDomain: 'health-6cd34.firebaseapp.com',
    storageBucket: 'health-6cd34.firebasestorage.app',
    measurementId: 'G-XRKJVWP1FE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUuKLqI3r8o2cfUa13qzQMgQEvcxhy3Gg',
    appId: '1:136918825702:android:d3ff86c084f60a6ce95927',
    messagingSenderId: '136918825702',
    projectId: 'health-6cd34',
    storageBucket: 'health-6cd34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQFrLT3i1Rx6WvNHC-vp4VNxIF8ort1is',
    appId: '1:136918825702:ios:aa514e6af7d75a14e95927',
    messagingSenderId: '136918825702',
    projectId: 'health-6cd34',
    storageBucket: 'health-6cd34.firebasestorage.app',
    iosBundleId: 'com.example.drApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQFrLT3i1Rx6WvNHC-vp4VNxIF8ort1is',
    appId: '1:136918825702:ios:aa514e6af7d75a14e95927',
    messagingSenderId: '136918825702',
    projectId: 'health-6cd34',
    storageBucket: 'health-6cd34.firebasestorage.app',
    iosBundleId: 'com.example.drApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLpFhV9aXaQ9nTv2Ss5hjWWTStvT79tB4',
    appId: '1:136918825702:web:0ab76207ffa616dae95927',
    messagingSenderId: '136918825702',
    projectId: 'health-6cd34',
    authDomain: 'health-6cd34.firebaseapp.com',
    storageBucket: 'health-6cd34.firebasestorage.app',
    measurementId: 'G-028CYHGJP3',
  );
}
